#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_TOUCHSCREEN_TIMER_PERIOD 10.0E-3
#define CONFIG_GAME_TIMER_PERIOD 45.0E-3

#define CONFIG_MAX_PLAYERS 2

// Speed of bullet
#define CONFIG_BULLET_DISTANCE_PER_SECOND 35
#define CONFIG_BULLET_DISTANCE_PER_TICK                                 \
  (CONFIG_BULLET_DISTANCE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

// How fast explosion radius increases/decreases per second
#define CONFIG_EXPLOSION_RADIUS_CHANGE_PER_SECOND 30
#define CONFIG_EXPLOSION_RADIUS_CHANGE_PER_TICK                                \
  (CONFIG_EXPLOSION_RADIUS_CHANGE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

#define CONFIG_COLOR_ENEMY_BULLET DISPLAY_RED
#define CONFIG_COLOR_PLAYER_BULLET DISPLAY_GREEN

#define CONFIG_EXPLOSION_MAX_RADIUS 25

#endif /* CONFIG_H */